nginx:
  build: ./nginx
  links:
   - "node1"
   - "node2"
   - "node3"
  ports:
   - "80:80"
node1:
  build: .
  volumes:
   - .:/app
  ports:
  - "8000"
  environment:
   NODE_ENV: development
node2:
  build: .
  volumes:
   - .:/app
  ports:
  - "8000"
  environment:
   NODE_ENV: development
node3:
  build: .
  volumes:
   - .:/app
  ports:
  - "8000"
  environment:
   NODE_ENV: development
